---
apiVersion: v1
data:
  config.yaml: |-
    server:
      port: 8080
    mongo:
      uri: "mongodb://devflow:devflow@mongodb.database.svc.cluster.local:27017/devflow?authSource=devflow"
      db: "devflow"
    log:
      level: "info"
      format: "json"   # json | console
    otel:
      endpoint: "trace-collector.observability.svc.cluster.local:4317"
      insecure: true   # 如果不启用 TLS
      service_name: "devflow"
    repo:
      address: "https://github.com/bsonger/manifests.git"
      path: "manifests"
    consul:
      address: http://consul-consul-server.consul.svc.cluster.local:8500
      key: app/devflow.yaml
    pyroscope: "http://pyroscope-distributor.monitoring.svc.cluster.local:4040"
    env: prod
kind: ConfigMap
metadata:
  labels:
    app: devflow
    env: prod
  name: devflow-config-volume-prod

---

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devflow
    monitoring: enabled
  name: devflow
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: devflow
  type: ClusterIP
status:
  loadBalancer: {}

---

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: devflow
    env: prod
  name: devflow-prod
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devflow
      env: prod
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30
      - setWeight: 50
      - pause:
          duration: 60
      - setWeight: 100
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: devflow
            stableSubsetName: stable
          virtualService:
            name: devflow
            routes:
            - devflow
  template:
    metadata:
      annotations:
        prometheus.io/job: devflow
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: devflow
        env: prod
        type: canary
    spec:
      containers:
      - env:
        - name: ENV
          value: prod
        - name: SERVICE_NAME
          value: devflow
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: registry.cn-hangzhou.aliyuncs.com/devflow/devflow@sha256:8d827adbbcb2388cffb07fbe621810f1b24a1ca036529bece7f30708c201f727
        imagePullPolicy: IfNotPresent
        name: devflow
        resources: {}
        volumeMounts:
        - mountPath: /etc/devflow/config
          name: devflow-config-volume-prod
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: devflow-config-volume-prod
        name: devflow-config-volume-prod
status:
  blueGreen: {}
  canary: {}

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: devflow
    env: prod
  name: devflow
spec:
  gateways:
  - istio-system/devflow-gateway
  hosts:
  - devflow.bei.com
  - devflow
  http:
  - name: devflow
    route:
    - destination:
        host: devflow
        port:
          number: 8080
        subset: stable
      weight: 100
    - destination:
        host: devflow
        port:
          number: 8080
        subset: canary

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: devflow
    env: prod
  name: devflow
spec:
  host: devflow
  subsets:
  - name: stable
  - name: canary

